%script to look at preycapture tracking data and define behavioral events
%and epochs to prep for running AR-HMM


%prey capture video tracking groupdata is generated by AnalyzeBonsaiTrackingData
%which is called by preycapturebatch using a file list such as preycapturefilelist

clear
close all

%groupdatadir= 'C:\Users\lab\Desktop\Legless crickets\combinedlegless';
%groupdatadir= 'D:\lab\Data\Legless crickets\combinedlegless';
%   groupdatadir= 'D:\lab\Data\826 mice bonsai';
groupdatadir= '/Volumes/wehrrig4D/lab/Data/lidocaine_groupdata'

% groupdatafilename='preycapture_groupdata';
groupdatafilename='preycapture_groupdata_lidocaine';

%adjust filenames to work on a mac & mount disk
if ismac
    mkdir /Volumes/wehrrig4D
    system('mount_smbfs smb://wehrrig4/D /Volumes/wehrrig4D')
    cd /Volumes/wehrrig4D
    groupdatadir= strrep(groupdatadir, '\', '/');
    groupdatadir= strrep(groupdatadir, 'C:', '/Volumes/wehrrig4C');
    groupdatadir= strrep(groupdatadir, 'D:', '/Volumes/wehrrig4D');
    
end

cd(groupdatadir)
load(groupdatafilename)
groupdata=groupdata_all;
numfiles=length(groupdata);
fprintf('\nanalyzing %d files', numfiles)
%groupdata is already trimmed to start_frame:stop_frame

%plot
for i=1:20
    figure
    hold on
    t=1:groupdata(i).numframes;
    t2=t(1:end-1);
    plot(t2, groupdata(i).speed)
    plot(t2, groupdata(i).cspeed)
    plot(t, groupdata(i).range)
    plot(t, groupdata(i).azimuth)
    
    contact=find(groupdata(i).range<2); %2 px = 1 mm
    plot(contact, 0*contact, 'ro')
    ylim([0 1200])
end

return
%if you want to watch the video, look for the appropriate file list in
%readme

TargetAcquisition=[];
TargetLoss=[];
Contact=[];
Escape=[];
Kill=[];
str={ 'Target Acquisition', ...
    'Target Loss', ...
    'Contact', ...
    'Escape', ...
    'Kill', ...
    'Undo last click'};
cont=1;
    h=msgbox('click to mark a frame');
while cont
    [x,y]=ginput(1);
    x=round(x);
    L=line(x*[1 1], ylim);
    
    [frametype, OK] = listdlg('PromptString', 'What kind of frame did you just click?',...
        'SelectionMode','single','ListString',str, 'CancelString', 'Exit');
    if OK
        switch str{frametype},
            case 'Target Acquisition',
                TargetAcquisition=[TargetAcquisition x];
            case 'Target Loss',
                TargetLoss=[TargetLoss x];
            case 'Contact',
                Contact=[Contact x];
            case 'Escape',
                Escape=[Escape x];
            case 'Kill',
                Kill=[Kill x];
            case 'Undo last click',
                set(L, 'visible', 'off')
        end
    else cont=0;
                set(L, 'visible', 'off')
    end
    
end % while

if Kill>t(end)
    Kill=t(end);
end
Search=0*t;
Pursuit=0*t;
Capture=0*t;



TargetAcquisition
TargetLoss
Contact
Escape
Kill

keyboard

% Hard-coded epochs from events
Pursuit(TargetAcquisition(1):TargetLoss(1))=1;
    Search(1:TargetAcquisition(1))=1;

    Pursuit(TargetAcquisition(2):TargetLoss(2))=1;
    Search(TargetLoss(1):TargetAcquisition(2))=1;

    Pursuit(TargetAcquisition(3):Contact(1))=1;

    Capture(contact)=1;

    
ylim([-220 1200])
plot(t, -200+Search*40)
plot(t, -150+Pursuit*40)
plot(t, -100+Capture*40)
text(0, -200+20, 'Search')
text(0, -150+20, 'Pursuit')
text(0, -100+20, 'Capture')


load('labelled_examples.mat')
n=length(labelled_examples);

labelled_examples(n+1)=groupdata(i);
labelled_examples(n+1).Search=Search;
labelled_examples(n+1).Pursuit=Pursuit;
labelled_examples(n+1).Capture=Capture;
labelled_examples(n+1).TargetAcquisition=TargetAcquisition;
labelled_examples(n+1).TargetLoss=TargetLoss;
labelled_examples(n+1).Contact=Contact;
labelled_examples(n+1).Escape=Escape;
labelled_examples(n+1).Kill=Kill;
labelled_examples(n+1).groupdata_index=i;
labelled_examples(n+1).groupdata_filename=groupdatafilename;

save labelled_examples labelled_examples



    








