function preycapturebatch_deeplab
%batch process prey capture files
%that were analyzed with deep lab cut

 %filelist='muscimol_fileslist';
 filelist='unilateral_injections_filelist';
%filelist='lidocaine_new_preycapturefilelist';
% analysis_dir= 'D:\lab\Data\lidocaine_groupdata';
% analysis_dir= 'D:\lab\Data\muscimol_groupdata';
 analysis_dir= 'D:\lab\Data\unilateral_groupdata';

files=eval(filelist);


if ismac
    analysis_dir= strrep(analysis_dir, '\', '/');
    analysis_dir= strrep(analysis_dir, 'C:', '/Volumes/C');
end
cd(analysis_dir)
delete analysis_plots.ps
delete preycapture_groupdata_all.mat
fprintf('\nAnalyzing %d files...', length(files))

readme='';
readme=[readme, sprintf('groupdata generated by %s running on filelist %s', mfilename, filelist)];
readme=[readme, sprintf('\nanalysis directory %s', analysis_dir )];
readme=[readme, sprintf('\nrun on %s', datestr(now))];
 %save preycapture_groupdata_muscimol readme
 %save preycapture_groupdata_lidocaine readme
save preycapture_groupdata_saline readme

j=0;
for i=1:length(files)
   % switch files(i).hemi
    %   case 'right'
%         case 'left'
        
    switch files(i).drug
%          case 'lidocaine'
        %case 'muscimol'
        case 'saline'
    
    cd(files(i).datapath)
    load preycapture_groupdata
    if ~isfield(groupdata, 'timepoints')
        groupdata.timepoints=[];
    end
    if ~isfield(groupdata, 'firstContact')
        groupdata.firstContact=0;
    end
    
    groupdata.start_frame=files(i).start_frame;
    groupdata.stop_frame=files(i).stop_frame;
    groupdata.firstcontact_frame=files(i).firstcontact_frame;
    groupdata.drug=files(i).drug;
    
    j=j+1;
    groupdata_all(j)=groupdata;
    
    
    if ~mod(i,10)
        fprintf('\nfile %d/%d', i, length(files))
    end
    end
%     end
end
cd(analysis_dir)
 %save preycapture_groupdata_muscimol groupdata_all -append
 %save preycapture_groupdata_lidocaine groupdata_all -append
save preycapture_groupdata_saline groupdata_all -append




