%batch process prey capture files

%files=leglesscricketsfilelist;
%analysis_dir= 'C:\Users\lab\Desktop\Legless crickets\combinedlegless';

% filelist='preycapturefilelist';
% analysis_dir= 'C:\Users\lab\Desktop\826 mice bonsai';

filelist='lidocaine_preycapturefilelist';
analysis_dir= 'D:\lab\Data\lidocaine_groupdata';

files=eval(filelist);


if ismac    
    analysis_dir= strrep(analysis_dir, '\', '/');
    analysis_dir= strrep(analysis_dir, 'C:', '/Volumes/C');
end
cd(analysis_dir)
delete analysis_plots.ps
delete preycapture_groupdata.mat
fprintf('\nAnalyzing %d files...', length(files))

readme='';
readme=[readme, sprintf('groupdata generated by %s running on filelist %s', mfilename, filelist)];
readme=[readme, sprintf('\nwhich calls AnalyzeBonsaiTrackingData')];
readme=[readme, sprintf('\nanalysis directory %s', analysis_dir )];
readme=[readme, sprintf('\nrun on %s', datestr(now))];
save preycapture_groupdata readme

for i=1:5%length(files)
    
    %we moved some data, try to correct
    files(i).datapath= 'D:\lab\Data\Injections_mice\Blue\7.11\pv2018-07-11T14_47_41.avi';

    
   AnalyzeBonsaiTrackingData( files(i).datapath, files(i).start_frame, files(i).stop_frame, analysis_dir)
   
   if ~mod(i,10)
       fprintf('\nfile %d/%d', i, length(files))
   end
end